### PR TITLE
fix: Fixing up postgres connection strings

### PR DESCRIPTION
**Pull request by masterkidan**
This is to fix issue #95

### CODE REVIEW

**Comment by go-jet** [comment]
Could you open PR for `develop` branch.  There are some changes made in generator that does not exist on master.  
`-dsn` flag was added with  https://github.com/go-jet/jet/pull/89.
I guess we could still replace flags with connection string for this function.

**Comment by masterkidan** [comment]
Updated to develop (hopefully I updated the above correctly).

**Comment by go-jet** [comment]
LGTM, but it seems there are some rebase conflicts.

**Comment by masterkidan** [comment]
Can you clarify where the conflicts are? I don't see them in the diff.

**Comment by go-jet** [comment]
It is probably because of merge commit a5c3d545fe376b87fc4eae36ca208fbf9a0fafad. But it is ok, squash and merge will work as well.

**Pull request merged**
