### PR TITLE
Replacing several test util function with a generic version

### PR DESCRIPTION
**Pull request by safaci2000**
ChangeLog:
  - updated several test utils with a generic PtrOf
  - updated references using iotils (Deprecated) with os equivalent import.

### CODE REVIEW

**Comment by safaci2000** [comment]
This is mostly fixing up the test tooling instead of using multiple implementation of BoolPtr, StringPtr etc, I removed all of them in favor of a PtroOf that uses generics.  Also, ioutils is deprecated so fixed up the imports.  All the functions have the same signature.

**Comment by go-jet** [comment]
Good catch. To eliminate `testutils` from the name we can go with a new package `ptr` that will contain just one method `Of`, so we would write then `ptr.Of(false)`. Also this method isn't specific just for test, so we can move the package to https://github.com/go-jet/jet/tree/master/internal/utils.

**Comment by safaci2000** [comment]
> Good catch. To eliminate `testutils` from the name we can go with a new package `ptr` that will contain just one method `Of`, so we would write then `ptr.Of(false)`. Also this method isn't specific just for test, so we can move the package to https://github.com/go-jet/jet/tree/master/internal/utils.

Done

**Comment by go-jet** [comment]
LGTM. It seems some tests are now failing because of changes in jet-test-data.

**Comment by go-jet** [comment]
> That's odd, that seems to go against how submodule are supposed to work. Do you mind if I just comment out the line:
> 
> ```
> checkout-testdata:
>    git submodule init
>    git submodule update
> # cd ./testdata && git fetch && git checkout master && git pull
> ```
> 
> if we're using submodule, it should have a commit ID that the testdata should honor. That line ignores all of it and always pulls master.

Yeah, you are right. Maybe move that line into `checkout-latest-testdat`.

**Comment by safaci2000** [comment]
> Yeah, you are right. Maybe move that line into `checkout-latest-testdat`.

Done

**Pull request merged**
